OrderApp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from order import views

urlpatterns = [
    path('admin/', admin.site.urls), # Default Admin Url
    path('tajindiaadmin/', include("accounts.urls")), # Custom Admin Url
    path('order/',include("order.urls")), # Order Application Url

    path('', views.index, name="index"), # Base URL
    re_path(r'^.*/$', views.index, name="index"), #Wild Card URL's
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [

    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('change_password/',auth_views.PasswordChangeView.as_view(template_name='accounts/update_item.html', success_url=reverse_lazy("accounts:items_list")),name='change_password'),
    path('', views.Index.as_view(), name="index"),
    path('items_list/', views.items_list, name='items_list'),
    path('options_list/', views.options_list, name='options_list'),
    path('update_item/<int:pk>', views.ItemsUpdateView.as_view(), name="update_item"),
    path('update_menu/<int:pk>', views.MenuUpdateView.as_view(), name="update_menu"),
    path('update_category/<int:pk>', views.CategoryUpdateView.as_view(), name="update_category"),
    path('item_availaible/<int:pk>', views.item_availaible, name="item_availaible"),
    path('menu_availaible/<int:pk>', views.menu_availaible, name="menu_availaible"),
    path('create_category/', views.CategoryCreateView.as_view(), name='create_category'),
    path('create_menu/', views.MenuCreateView.as_view(), name='create_menu'),
    path('create_item/', views.ItemsCreateView.as_view(), name='create_item'),
    path('create_table/', views.TableCreateView.as_view(), name='create_table'),
    path('view_table/<int:pk>', views.view_table, name='view_table'),
    path('view_order/<int:pk>', views.view_order, name='view_order'),
    path('feedback_list/', views.feedback_list, name="feedback_list"),
    path('create_option1/', views.Option1CreateView.as_view(), name='create_option1'),
    path('create_option2/', views.Option2CreateView.as_view(), name='create_option2'),
    path('create_extras/', views.ExtrasCreateView.as_view(), name='create_extras'),
    path('update_option1/<int:pk>', views.Option1UpdateView.as_view(), name='update_option1'),
    path('update_option2/<int:pk>', views.Option2UpdateView.as_view(), name='update_option2'),
    path('update_extras/<int:pk>', views.ExtrasUpdateView.as_view(), name='update_extras'),
    path('delete_option1/<int:pk>', views.Option1DeleteView.as_view(), name='delete_option1'),
    path('delete_option2/<int:pk>', views.Option2DeleteView.as_view(), name='delete_option2'),
    path('delete_extras/<int:pk>', views.ExtrasDeleteView.as_view(), name='delete_extras'),
    path('delete_feedback/<int:pk>', views.FeedbackDeleteView.as_view(), name='delete_feedback'),
    path('table_availaible/<int:tableNumber>', views.table_availaible, name='table_availaible'),
    path('table_unavailaible/<int:tableNumber>', views.table_unavailaible, name='table_unavailaible'),
    path('create_orderitem/<int:tableNumber>', views.create_orderitem, name='create_orderitem'),
    path('update_cart/', views.update_cart, name='update_cart'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [

    path('index', views.index, name="index"),
    path('menu/<int:tableNumber>/', views.menu, name="menu"),
    path('placeOrder', views.placeOrder, name="placeOrder"),
    path('cart/<int:tableNumber>/', views.cart, name="cart"),
    path('order_list/<int:tableNumber>', views.orderCart, name="order_list"),
    path('confirmOrder/<int:tableNumber>', views.confirmOrder, name="confirmOrder"),
    path('thanks/<int:tableNumber>', views.thanks, name='thanks'),
    path('add_to_cart/<int:pk>/<int:tableNumber>', views.add_to_cart, name="add_to_cart"),
    path('remove_from_cart/<int:pk>/<int:tableNumber>', views.remove_from_cart, name="remove_from_cart"),
    path('remove_addOn/<int:pk>/<int:tableNumber>', views.remove_addOn, name="remove_addOn"),
    path('updateCart', views.updateCart, name="updateCart"),
    path('waiter/', views.CallWaiter, name='waiter'),
    path('menuThanks/<int:tableNumber>', views.menu_from_thanks, name='menuThanks'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.forms import ModelForm

from order.models import OrderItem

class OrderItemForm(ModelForm):
    class Meta:
        model = OrderItem
        fields = ['item', 'menu', 'option1', 'option2', 'addOn', 'person', 'quantity']

accounts/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, ListView, DetailView, TemplateView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages
from django.http import HttpResponse
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync
from django import forms
import json

from items.models import Table, Category, Item, Menu, Option1, Option2, AddOn
from order.models import Order, OrderItem, Feedback
from .forms import OrderItemForm
from django.forms.models import modelform_factory

# Create your views here.
class ModelFormWidgetMixin(object):
    def get_form_class(self):
        return modelform_factory(self.model, fields=self.fields, widgets=self.widgets)

class Index(LoginRequiredMixin, ListView):
    model = Table
    template_name = 'accounts/index.html'

@login_required
def update_cart(request):
    if request.is_ajax and request.method == "GET":
        myOrderDict = {}
        for key in request.GET:
            quantity = request.GET[key]
            key = key.split('[')[1].split(']')[0]
            order_item = OrderItem.objects.get(pk=int(key))
            order_item.quantity = quantity
            if int(quantity) == 0:
                order_item.delete()
            else:
                order_item.save()
    return HttpResponse("Success")

@login_required
def create_orderitem(request, tableNumber):
    context = {}
    context['form'] = OrderItemForm()
    context['tableNumber'] = tableNumber
    if request.POST:
        form = OrderItemForm(request.POST)
        if form.is_valid():
            item = form.cleaned_data.get("item")
            menu = form.cleaned_data.get('menu')
            if item and menu:
                messages.warning(request, "Please select only one, either item or menu. You can't select both")
                return render(request, 'accounts/update_item.html', context)
            if not item and not menu:
                messages.warning(request, "Both item and menu can't be empty. You must select one")
                return render(request, 'accounts/update_item.html', context)
            if item:
                option1 = form.cleaned_data.get('option1')
                option2 = form.cleaned_data.get('option2')
                addOn = form.cleaned_data.get('addOn')
                quantity = form.cleaned_data.get('quantity')
                table = Table.objects.get(tableNumber=tableNumber)
                order_item = OrderItem.objects.create(table=table, item=item, option1=option1, option2=option2, addOn=addOn, quantity=quantity, ordered=True, paid=False)
                order = Order.objects.get(table = table, ordered=False)
                order_item.save()
                order.item.add(order_item)
                order.save()
                return redirect("accounts:view_table", pk=tableNumber)
            if menu:
                option1 = form.cleaned_data.get('option1')
                person = form.cleaned_data.get('person')
                if not person:
                    messages.warning(request, "Please select number of person for menu.")
                    return render(request, 'accounts/update_item.html', context)
                quantity = form.cleaned_data.get('quantity')
                table = Table.objects.get(tableNumber=tableNumber)
                order_item = OrderItem.objects.create(table=table, menu=menu, option1=option1, person=person, quantity=quantity, ordered=True, paid=False)
                order = Order.objects.get(table = table, ordered=False)
                order_item.save()
                order.item.add(order_item)
                order.save()
                return redirect("accounts:view_table", pk=tableNumber)
    return render(request, 'accounts/update_item.html', context)

@login_required
def items_list(request):
    context = { 'menu_list' : Menu.objects.all(), 'category_list' : Category.objects.all() }
    return render(request, 'accounts/items_list.html', context)

@login_required
def options_list(request):
    context = { 'option1' :  Option1.objects.all(), 'option2' : Option2.objects.all(), 'addOn' : AddOn.objects.all() }
    return render(request, 'accounts/options_list.html', context)

@login_required
def feedback_list(request):
    context = { 'feedback' :  Feedback.objects.all().order_by("-time") }
    return render(request, 'accounts/feedback_list.html', context)

@login_required
def item_availaible(request, pk):
    item = Item.objects.get(pk=pk)
    if item.availaible:
        item.availaible = False
    else:
        item.availaible = True
    item.save()
    return redirect("accounts:items_list")

@login_required
def menu_availaible(request, pk):
    item = Menu.objects.get(pk=pk)
    if item.availaible:
        item.availaible = False
    else:
        item.availaible = True
    item.save()
    return redirect("accounts:items_list")

class ItemsUpdateView(LoginRequiredMixin, ModelFormWidgetMixin, UpdateView):
    model = Item
    widgets = {
        'options': forms.CheckboxSelectMultiple,
        'suggestions' : forms.CheckboxSelectMultiple,
    }
    template_name = 'accounts/update_item.html'
    fields = [
              "category",
              "article_number",
              "name",
              "price",
              "description",
              "veg",
              "vegan",
              "option1",
              "addOn",
              "options",
              "suggestions",
              "image",
    ]
    success_url = reverse_lazy("accounts:items_list")

class CategoryUpdateView(LoginRequiredMixin, ModelFormWidgetMixin, UpdateView):
    model = Category
    widgets = {
        'options': forms.CheckboxSelectMultiple,
        'extras' : forms.CheckboxSelectMultiple,
    }
    template_name = 'accounts/update_item.html'
    fields = [
              "name",
              "veg",
              "vegan",
              "options",
              "extras",
              "addOnPrice",
              "images",
    ]
    success_url = reverse_lazy("accounts:items_list")

class MenuUpdateView(LoginRequiredMixin, ModelFormWidgetMixin, UpdateView):
    model = Menu
    widgets = {
        'options': forms.CheckboxSelectMultiple,
    }
    template_name = 'accounts/update_menu.html'
    fields = [
              "name",
              "veg",
              "vegan",
              "body",
              "price2",
              "price3",
              "price4",
              "options",
              "image",
    ]
    labels = {
        'price2' : "Price for 2 persons",
        'price3' : "Price for 3 persons",
        'price4' : "Price for 4 persons",
    }
    success_url = reverse_lazy("accounts:items_list")

class ItemsCreateView(LoginRequiredMixin, ModelFormWidgetMixin, CreateView):
    model = Item
    widgets = {
        'options': forms.CheckboxSelectMultiple,
        'suggestions' : forms.CheckboxSelectMultiple,
    }
    template_name = 'accounts/update_item.html'
    fields = [
              "category",
              "article_number",
              "name",
              "price",
              "description",
              "veg",
              "vegan",
              "option1",
              "addOn",
              "options",
              "suggestions",
              "image",
    ]
    success_url = reverse_lazy("accounts:items_list")

class CategoryCreateView(LoginRequiredMixin, ModelFormWidgetMixin, CreateView):
    model = Category
    widgets = {
        'options': forms.CheckboxSelectMultiple,
        'extras' : forms.CheckboxSelectMultiple,
    }
    template_name = 'accounts/update_item.html'
    fields = [
              "name",
              "veg",
              "vegan",
              "options",
              "extras",
              "addOnPrice",
              "images",
    ]
    success_url = reverse_lazy("accounts:items_list")

class MenuCreateView(LoginRequiredMixin, ModelFormWidgetMixin, CreateView):
    model = Menu
    widgets = {
        'options': forms.CheckboxSelectMultiple,
    }
    template_name = 'accounts/update_menu.html'
    fields = [
              "name",
              "veg",
              "vegan",
              "body",
              "price2",
              "price3",
              "price4",
              "options",
              "image",
    ]
    labels = {
        'price2' : "Price for 2 persons",
        'price3' : "Price for 3 persons",
        'price4' : "Price for 4 persons",
    }
    success_url = reverse_lazy("accounts:items_list")

class TableCreateView(LoginRequiredMixin, CreateView):
    model = Table
    template_name = 'accounts/update_item.html'
    fields = ["tableNumber"]
    success_url = reverse_lazy("accounts:index")

class Option1UpdateView(LoginRequiredMixin, UpdateView):
    model = Option1
    template_name = "accounts/update_item.html"
    fields = ["name"]
    success_url = reverse_lazy("accounts:options_list")

class Option1CreateView(LoginRequiredMixin, CreateView):
    model = Option1
    template_name = "accounts/update_item.html"
    fields = ["name"]
    success_url = reverse_lazy("accounts:options_list")

class Option1DeleteView(LoginRequiredMixin, DeleteView):
    model = Option1
    template_name = "accounts/delete_item.html"
    fields = ["name"]
    success_url = reverse_lazy("accounts:options_list")

class Option2UpdateView(LoginRequiredMixin, UpdateView):
    model = Option2
    template_name = "accounts/update_item.html"
    fields = ["name"]
    success_url = reverse_lazy("accounts:options_list")

class Option2CreateView(LoginRequiredMixin, CreateView):
    model = Option2
    template_name = "accounts/update_item.html"
    fields = ["name"]
    success_url = reverse_lazy("accounts:options_list")

class Option2DeleteView(LoginRequiredMixin, DeleteView):
    model = Option2

templates/accounts/delete_item.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Taj India Restaurant</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

  </head>
  <body>
    <div class="split left" data-spy="scroll" data-target=".navbar" data-offset="50">
      <!--  Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand">Taj India Restaurant</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:index' %}">Tables</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:items_list' %}">Items</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:options_list' %}">Options</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:feedback_list' %}">Feedback</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Profile
          </a>
          <div class="dropdown-menu navbar-dark bg-dark" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'accounts:change_password' %}" style="color:white;">Change Password</a>
            <a class="dropdown-item" href="{% url 'accounts:logout' %}" style="color:white;">Logout</a>
          </div>
        </li>
      </ul>
    </div>
  </nav>
      <!--  Navbar-->


    <div class="container">
    <div class="jumbotron">
      <form method="POST" class="form">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" class="btn btn-danger">
      </form>
    </div>

    </div>
  </body>
  </html>

templates/accounts/items_list.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Taj India Restaurant</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="split left" data-spy="scroll" data-target=".navbar" data-offset="50">
    <!--  Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand">Taj India Restaurant</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:index' %}">Tables</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:items_list' %}">Items</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:options_list' %}">Options</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:feedback_list' %}">Feedback</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profile
        </a>
        <div class="dropdown-menu navbar-dark bg-dark" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'accounts:change_password' %}" style="color:white;">Change Password</a>
          <a class="dropdown-item" href="{% url 'accounts:logout' %}" style="color:white;">Logout</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
    <!--  Navbar-->
    <div class="jumbotron">
      <h1 class="float-left">Items List</h1>
      <a class="btn btn-primary btn-lg float-right" href="{% url 'accounts:create_category' %}">Add Category</a>
      <a class="btn btn-primary btn-lg float-right mr-3" href="{% url 'accounts:create_item' %}">Add Item</a>
    </div>


    <div class="container">
    <div class="jumbotron">
      <div class="d-flex justify-content-between align-items-center">
      <h2>Menus</h2>
      <a class="btn btn-primary" href="{% url 'accounts:create_menu' %}">Add New Menu</a>
      </div>
      <ul class="list-group">
        {% for menu in menu_list.all %}
            <li class="list-group-item list-group-item-action">
            {{ menu.name }}
            <a href="{% url 'accounts:update_menu' pk=menu.pk %}" class="btn btn-primary float-right">Edit Menu</a>
            {% if menu.availaible %}
            <a href="{% url 'accounts:menu_availaible' pk=menu.pk %}" class="btn btn-danger float-right mr-3">Make Unavailable</a>
            {% else %}
            <a href="{% url 'accounts:menu_availaible' pk=menu.pk %}" class="btn btn-primary float-right mr-3 pl-4 pr-3">Make Available</a>
            {% endif %}
          </li>
        {% endfor %}
      </ul>
    </div>
    </div>

    {% for category in category_list %}
      <div class="container">
      <div class="jumbotron">
        <div class="d-flex justify-content-between align-items-center">
        <h2>{{ category.name }}</h2>
        <a class="btn btn-primary" href="{% url 'accounts:update_category' pk=category.pk %}">Edit Category</a>
        </div>
        <ul class="list-group">
          {% for items in category.products.all %}
            <li class="list-group-item list-group-item-action">
            {{ items.name }}
            <a href="{% url 'accounts:update_item' pk=items.pk %}" class="btn btn-primary float-right">Edit Item</a>
            {% if items.availaible %}
            <a href="{% url 'accounts:item_availaible' pk=items.pk %}" class="btn btn-danger float-right mr-3">Make Unavailable</a>
            {% else %}
            <a href="{% url 'accounts:item_availaible' pk=items.pk %}" class="btn btn-primary float-right mr-3 pl-4 pr-3">Make Available</a>
            {% endif %}
            </li>
          {% endfor %}
        </ul>
      </div>
      </div>
    {% endfor %}

  </body>
</html>

templates/accounts/options_list.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Taj India Restaurant</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="split left" data-spy="scroll" data-target=".navbar" data-offset="50">
      <!--  Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand">Taj India Restaurant</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:index' %}">Tables</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:items_list' %}">Items</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:options_list' %}">Options</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:feedback_list' %}">Feedback</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Profile
          </a>
          <div class="dropdown-menu navbar-dark bg-dark" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'accounts:change_password' %}" style="color:white;">Change Password</a>
            <a class="dropdown-item" href="{% url 'accounts:logout' %}" style="color:white;">Logout</a>
          </div>
        </li>
      </ul>
    </div>
  </nav>
      <!--  Navbar-->
    <div class="jumbotron">
      <h1 class="float-left">Options List</h1>
    </div>

    <div class="container">
    <div class="jumbotron">
      <div class="d-flex justify-content-between align-items-center">
      <h2>Category Specific Options</h2>
      <a class="btn btn-primary" href="{% url 'accounts:create_option1' %}">Add New Option</a>
      </div>
      <ul class="list-group">
        {% for option in option1.all %}
            <li class="list-group-item list-group-item-action">
            {{ option.name }}
            <a href="{% url 'accounts:update_option1' pk=option.pk %}" class="btn btn-primary float-right">Edit Option</a>
            <a href="{% url 'accounts:delete_option1' pk=option.pk %}" class="btn btn-danger float-right mr-3">Delete Option</a>
          </li>
        {% endfor %}
      </ul>
    </div>
    </div>

    <div class="container">
    <div class="jumbotron">
      <div class="d-flex justify-content-between align-items-center">
      <h2>Item Specific Options</h2>
      <a class="btn btn-primary" href="{% url 'accounts:create_option2' %}">Add New Option</a>
      </div>
      <ul class="list-group">
        {% for option in option2.all %}
            <li class="list-group-item list-group-item-action">
            {{ option.name }}
            <a href="{% url 'accounts:update_option2' pk=option.pk %}" class="btn btn-primary float-right">Edit Option</a>
            <a href="{% url 'accounts:delete_option2' pk=option.pk %}" class="btn btn-danger float-right mr-3">Delete Option</a>
          </li>
        {% endfor %}
      </ul>
    </div>
    </div>

    <div class="container">
    <div class="jumbotron">
      <div class="d-flex justify-content-between align-items-center">
      <h2>Extras Options</h2>
      <a class="btn btn-primary" href="{% url 'accounts:create_extras' %}">Add New Option</a>
      </div>
      <ul class="list-group">
        {% for option in addOn.all %}
            <li class="list-group-item list-group-item-action">
            {{ option.item }}
            <a href="{% url 'accounts:update_extras' pk=option.pk %}" class="btn btn-primary float-right">Edit Option</a>
            <a href="{% url 'accounts:delete_extras' pk=option.pk %}" class="btn btn-danger float-right mr-3">Delete Option</a>
          </li>
        {% endfor %}
      </ul>
    </div>
    </div>

  </body>
</html>