OrderApp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from order import views

urlpatterns = [
    path('admin/', admin.site.urls), # Default Admin Url
    path('tajindiaadmin/', include("accounts.urls")), # Custom Admin Url
    path('order/',include("order.urls")), # Order Application Url

    path('', views.index, name="index"), # Base URL
    re_path(r'^.*/$', views.index, name="index"), #Wild Card URL's
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [

    path('index', views.index, name="index"),
    path('menu/<int:tableNumber>/', views.menu, name="menu"),
    path('placeOrder', views.placeOrder, name="placeOrder"),
    path('cart/<int:tableNumber>/', views.cart, name="cart"),
    path('order_list/<int:tableNumber>', views.orderCart, name="order_list"),
    path('confirmOrder/<int:tableNumber>', views.confirmOrder, name="confirmOrder"),
    path('thanks/<int:tableNumber>', views.thanks, name='thanks'),
    path('add_to_cart/<int:pk>/<int:tableNumber>', views.add_to_cart, name="add_to_cart"),
    path('remove_from_cart/<int:pk>/<int:tableNumber>', views.remove_from_cart, name="remove_from_cart"),
    path('remove_addOn/<int:pk>/<int:tableNumber>', views.remove_addOn, name="remove_addOn"),
    path('updateCart', views.updateCart, name="updateCart"),
    path('waiter/', views.CallWaiter, name='waiter'),
    path('menuThanks/<int:tableNumber>', views.menu_from_thanks, name='menuThanks'),
]

items/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Table(models.Model):
    tableNumber = models.IntegerField(unique = True, verbose_name=('Table Number'))
    availaible = models.BooleanField(default = True)
    unique_number = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return "Table Number {}".format(self.tableNumber)

class AddOn(models.Model):
    item = models.CharField(max_length = 256)

    def __str__(self):
        return self.item

class Option1(models.Model):
    name = models.CharField(max_length = 256)

    def __str__(self):
        return self.name

class Option2(models.Model):
    name = models.CharField(max_length = 256)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length = 512, unique = True)
    veg = models.BooleanField(default = False)
    vegan = models.BooleanField(default=False)
    images = models.ImageField(upload_to = 'items/Category', default='items/Category/default.jpg')
    addOnPrice = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True, verbose_name=('Extra Option Price'))
    extras = models.ManyToManyField(AddOn, blank = True, related_name = 'category')
    options = models.ManyToManyField(Option1, blank = True, related_name = 'category')

    def __str__(self):
        return self.name

    def set_image_to_default(self):
        self.avatar.delete(save=False)  # delete old image file
        self.avatar = DEFAULT
        self.save()

class Menu(models.Model):
    name = models.CharField(max_length = 512)
    veg = models.BooleanField(default = False)
    vegan = models.BooleanField(default=False)
    availaible = models.BooleanField(default = True)
    price2 = models.DecimalField( max_digits=8, decimal_places=2, verbose_name=('Price for 2 person'))
    price3 = models.DecimalField( max_digits=8, decimal_places=2, verbose_name=('Price for 3 person'))
    price4 = models.DecimalField( max_digits=8, decimal_places=2, verbose_name=('Price for 4 person'))
    options = models.ManyToManyField(Option1, blank = True, related_name = 'menu')
    body = RichTextField(blank = True, null = True)
    image = models.ImageField(blank = True, null = True, upload_to = 'items/menu')

    def __str__(self):
        return "{} with pk {}".format(self.name,self.pk)

class Item(models.Model):
    category = models.ForeignKey(Category, related_name = 'products', on_delete = models.CASCADE)
    article_number = models.IntegerField(unique = True, blank=True, null=True)
    name = models.CharField(max_length=512)
    price = models.DecimalField( max_digits=8, decimal_places=2)
    availaible = models.BooleanField(default = True)
    option1 = models.BooleanField(default = False, verbose_name=('Show Category Options'))
    addOn = models.BooleanField(default=False, verbose_name=('Extras'))
    veg = models.BooleanField(default = False)
    vegan = models.BooleanField(default = False)
    description = models.TextField(max_length = 2000, blank = True, null = True)
    suggestions = models.ManyToManyField("Item", blank = True, symmetrical=False, related_name = 'related_to')
    options = models.ManyToManyField(Option2, blank = True, related_name = 'Items', verbose_name=('Show Following options'))
    image = models.ImageField(blank = True, null = True, upload_to = 'items/items')

    def __str__(self):
        if self.article_number:
            return "{}. {}".format(self.article_number, self.name)
        else :
            return self.name

order/forms.py
from django import forms

class CartForm(forms.Form):

    starter = forms.BooleanField()
    description = forms.CharField(max_length=1000, required = False)

items/views.py
from django.shortcuts import render

# Create your views here.

order/views.py
from django.views.generic import TemplateView
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_protect
from django.utils import timezone
import json, datetime, random
from django.core import serializers
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync

from items.models import Table, Category, Item, Menu
from order.models import Order, OrderItem, Feedback
from order.forms import CartForm

def get_time():
    currentTime = datetime.datetime.now()
    time = ('{}:{}'.format(currentTime.hour, currentTime.minute))
    d = datetime.datetime.strptime(time, "%H:%M")
    return d.strftime("%I:%M %p")

def index(request):

    if request.method == 'POST':
        tableNumber = request.POST['tableNumber']
        table = Table.objects.filter(tableNumber = tableNumber)
        if table:
            table = table[0]
            if table.availaible:
                channel_layer = get_channel_layer()
                message = "Table Number {} is now active".format(tableNumber)
                text = { 'tableNumber':tableNumber, 'message':message, 'type':'Active', 'time':get_time() }
                async_to_sync(channel_layer.group_send)('broadcast', { 'type': 'websocket.message', 'text': json.dumps(text) })
                messages.warning(request, "This device is the primary device for table no. {}. Please use this device to place order".format(tableNumber))
                return redirect("order:menu", tableNumber = tableNumber)
            else:
                unique_number = int(request.COOKIES.get('unique_number', 404))
                if table.unique_number == unique_number:
                    messages.warning(
                        request, "This device is the primary device for table no. {}. Please use this device to place order".format(tableNumber))
                    return redirect("order:menu", tableNumber=tableNumber)

                else:
                    context = { 'tableNumber':tableNumber }
                    context['category_list'] = Category.objects.all()
                    context['menu_list'] = Menu.objects.all()
                    messages.warning(request, "Please check the menu and use the primary device on your table to place the order")
                    return render(request, 'order/staticmenu.html', context)
        else:
            messages.warning(request, "Please enter correct table number")
            return render(request, 'order/index.html')

    return render(request, 'order/index.html')

def menu_from_thanks(request, tableNumber):
    try:
        table = Table.objects.get(tableNumber = tableNumber)
        if not table.availaible:
            unique_number = int(request.COOKIES.get('unique_number', 404))
            if table.unique_number == unique_number:
                channel_layer = get_channel_layer()
                message = "Table Number {} is now active".format(tableNumber)
                text = { 'tableNumber':tableNumber, 'message':message, 'type':'Active', 'time':get_time() }
                async_to_sync(channel_layer.group_send)('broadcast', { 'type': 'websocket.message', 'text': json.dumps(text) })
                return redirect("order:menu", tableNumber = tableNumber)
            else:
                messages.warning(request, "Please enter correct table number")
                return render(request, 'order/index.html')
        else:
            channel_layer = get_channel_layer()
            message = "Table Number {} is now active".format(tableNumber)
            text = { 'tableNumber':tableNumber, 'message':message, 'type':'Active', 'time':get_time() }
            async_to_sync(channel_layer.group_send)('broadcast', { 'type': 'websocket.message', 'text': json.dumps(text) })
            return redirect("order:menu", tableNumber = tableNumber)
    except:
        messages.warning(request, "Please enter correct table number")
        return render(request, 'order/index.html')

def menu(request, tableNumber):

    try:
        table = Table.objects.get(tableNumber = tableNumber)
        context = { 'tableNumber':tableNumber }
        if table.availaible:
            table.unique_number = random.randint(100000,999999)
            table.availaible = False
            table.save()
            context['category_list'] = Category.objects.all()
            context['menu_list'] = Menu.objects.all()
            response = render(request, 'order/ordermenu.html', context)
            response.set_cookie('unique_number', table.unique_number, 3600*24*3)
            return response

        else:
            unique_number = int(request.COOKIES.get('unique_number', 404))
            if table.unique_number == unique_number:
                context['category_list'] = Category.objects.all()
                context['menu_list'] = Menu.objects.all()
                return render(request, 'order/ordermenu.html', context)
            else:
                messages.warning(request, "Sorry this table is already equipped")
                return redirect("order:index")

    except ObjectDoesNotExist:
        messages.warning(request, "No such table exist")
        return redirect("order:index")

def cart(request, tableNumber):

    try:

        table = Table.objects.get(tableNumber = tableNumber)
        context = { 'tableNumber':tableNumber }
        if not table.availaible:
            unique_number = int(request.COOKIES.get('unique_number', 404))
            if table.unique_number == unique_number:
                order = Order.objects.filter(table = table, ordered = False)
                if order:
                    context['order'] = order[0]
                    context['order_items'] = order[0].item.filter(paid=False, ordered=False)
                    if not context['order_items']:
                        messages.warning(request, "Your cart is currently empty.")
                    return render(request, 'order/cart.html', context)
                else:
                    messages.warning(request, "Sorry, you do not have any active order")
                    return redirect("order:menu", tableNumber=tableNumber)
            else:
                messages.warning(request, "Sorry this table is already equipped")
                return redirect("order:index")

        else:
            return redirect("order:index")

    except ObjectDoesNotExist:
        messages.warning(request, "OOPs! Something went wrong")
        return redirect("order:index")

def orderCart(request, tableNumber):

    try:
        table = Table.objects.get(tableNumber = tableNumber)
        context = { 'tableNumber':tableNumber }
        if not table.availaible:
            unique_number = int(request.COOKIES.get('unique_number', 404))
            if table.unique_number == unique_number:
                order = Order.objects.filter(table = table, ordered = False)
                if order:
                    context['order_items'] = order[0].item.filter(ordered=True, paid=False)
                    if not context['order_items']:
                        messages.warning(request, "You have not placed any order yet")
                    context['order'] = order[0]
                    return render(request, 'order/orderCart.html', context)
                else:
                    messages.warning(request, "Sorry, you do not have any active order")
                    return redirect("order:menu", tableNumber=tableNumber)
            else:
                messages.warning(request, "Sorry, this table is already equipped")
                return redirect("order:index")

        else:
            return redirect("order:index")

    except ObjectDoesNotExist:
        messages.warning(request, "OOPs! something went wrong")
        return redirect("order:index")

def placeOrder(request):

    if request.is_ajax and request.method == "GET":

        myOrderDict = {}
        for key in request.GET:
            if (key.startswith('order')):

                value = json.loads(request.GET[key])
                key = key.split('[')[1].split(']')[0]
                myOrderDict[key] = value

        tableNumber = request.GET['tableNumber']
        print(myOrderDict)

        table = Table.objects.get(tableNumber = tableNumber)
        order_qs = Order.objects.filter(table = table, ordered = False)
        order = Order.objects
        if order_qs:                                                            #Order already exist
            order = order_qs[0]
        else:
            order = Order.objects.create(table = table, ordered=False, orderDate = timezone.now())
        for key in myOrderDict:
            pk = int(key[4:])
            myOrder = myOrderDict[key]
            if( key[:4] == 'item' ):                                        #Update items quantity
                item = Item.objects.get(pk = pk)
                if (item.option1 and item.options.count()):
                    for option1 in myOrder:
                        for option2 in myOrder[option1]:
                            if isinstance(myOrder[option1][option2], dict):
                                for addOn in myOrder[option1][option2]:
                                    if addOn == "None":
                                        order_item_qs = OrderItem.objects.filter(
                                            table=table, ordered=False, item=item, option1=option1, option2=option2, addOn=None)
                                        if order_item_qs:
                                            order_item = order_item_qs[0]
                                            order_item.quantity = myOrder[option1][option2][addOn]
                                            order_item.save()
                                            order.save()
                                        else:

templates/order/cart.html
{% extends "order/base.html" %} {% load static %} {% block head_block %}

<link rel="stylesheet" href="{% static 'css/order/cart.css' %}" /> {% endblock %} {% block body_block %}

<!--Pop Up Box-->
<div class="modal" id="modal2" data-animation="mixInAnimations">
    <div class="modal-dialog">
        <header class="modal-header">Call Waiter</header>
        <section class="modal-content">
            <p>Someone will be with you shortly.</p>
            <button id="close" class="close-modal" aria-label="close modal" data-close>
        Close
      </button>
        </section>
    </div>
</div>

<!--Pop Up Box-->

{% if messages %}
{% for message in messages %}

<div class="modal1 animated slideInUp" id="modal">
  <div class="modal-dialog1">
    <header class="modal-header">Alert

    </header>
    <section class="modal-content">
      <p>{{ message }}</p>
      <button id="close" class="close-modal1" data-dismiss="alert" onclick="this.parentElement.parentElement.parentElement.style.display='none'">
        Close
      </button>
    </section>
  </div>
</div>
{% endfor %}
{% endif %}


<!--Navbar Starts Here -->
<nav id="navbar" class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button style="color: #FFECB1" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span style="background-color: #FFECB1" class="sr-only">Toggle navigation</span>
        <span style="background-color: #FFECB1" class="icon-bar"></span>
        <span style="background-color: #FFECB1" class="icon-bar"></span>
        <span style="background-color: #FFECB1" class="icon-bar"></span>
      </button>
            <a class="navbar-brand" onclick="addMoreItems({{ tableNumber }})"><img src="{% static 'images/order/Taj_india_Logo.png' %}" alt=""></a>
            <a href="#" id="callButton" class="dropdown dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><img src="{% static 'images/order/waiter.png' %}"></a>
            <ul class="dropdown-menu">
                <li><a href="#" class="open-modal" data-open="modal2" onclick="CallWaiter({{ tableNumber }})"><i class="fas fa-phone-volume"></i>&nbsp;&nbsp; Call Waiter</a></li>
            </ul>

        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a onclick="addMoreItems({{ tableNumber }})">Menu Card</a></li>
                <li><a onclick="Order({{ tableNumber }})">Cart</a></li>
                <li><a onclick="OrderList({{ tableNumber }})">Order Details</a></li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>
<!--Navbar Ends Here-->



<!--Parralax Starts Here-->
<div class="header" style="background-image: url({% static 'images/order/parallex/cart.jpg' %})">
    <h1 id="heading">YOUR CART</h1>
    <h3 id="subheading">Here Food is cooked with love.</h3>
</div>

<!--Parralax Ends Here-->
{% for order_item in order_items.all %} {% if order_item.ordered %} {% else %}
<section id="order" class="order_item{{ order_item.pk }}" data-id="order_item{{ order_item.pk }}">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-7">
                <p class="itemname">{% if order_item.item %}{% if order_item.item.article_number %}{{ order_item.item.article_number }}. {% endif %}{% endif %}{{ order_item.get_name }}</p>
            </div>
            <div class="col-xs-5">
                <p class="quantityBtn">
                    <span class="minusBtn incdecbutton" onclick="functionMinus('order_item{{ order_item.pk }}')">-</span>
                    <span class="mainBtn order_item{{ order_item.pk }}" data-id="{% if order_item.item %}item{{ order_item.item.pk }}{% else %}menu{{ order_item.menu.pk }}{% endif %}" data-addOn="{% if order_item.item %}{% if order_item.item.addOn %}True{% else %}False{% endif %}{% else %}False{% endif %}">{{ order_item.quantity }}</span>
                    <span class="plusBtn incdecbutton" onclick="functionPlus('order_item{{ order_item.pk }}')">+</span>
                </p>
            </div>
        </div>
        <div class="row">
            {% if order_item.person %}
            <div class="col-xs-7">
                <p class="spicelvl personorder_item{{ order_item.pk }}" data-id="{{ order_item.person }}">(for {{ order_item.person }} person)</p>
            </div>
            {% endif %} {% if order_item.option1 %}
            <div class="col-xs-7">
                <p class="spicelvl order_item{{ order_item.pk }}" data-id="{{ order_item.option1 }}">({{ order_item.option1 }})</p>
            </div>
            {% else %}
            <div class="col-xs-7">
                <p class="spicelvl">Price</p>
            </div>
            {% endif %} {% if order_item.option2 %}
            <div class="col-xs-7">
                <p class="spicelvl option2order_item{{ order_item.pk }}" data-id="{{ order_item.option2 }}">({{ order_item.option2 }})</p>
            </div>
            {% endif %} {% if order_item.addOn %}
            <div class="col-xs-7">
                <p class="spicelvl addOnorder_item{{ order_item.pk }}" data-id="{{ order_item.addOn }}">{{ order_item.addOn }} (+{{ order_item.item.category.addOnPrice }} €)</p>
            </div>
            {% endif %}
            <div class="col-xs-5">
                <p class="price priceorder_item{{ order_item.pk }}" data-id="{{ order_item.getPrice }}">€ {{ order_item.getPrice }}</p>
            </div>
            <div class="row">
            </div>
            <div class="col-xs-12">
                <input type="text" placeholder="Any instructions...(optional)" onfocus="this.placeholder = '' " class="message order_item{{ order_item.pk }}" {% if order_item.description %}value="{{ order_item.description }}" {% endif %}>
            </div>
        </div>
    </div>
</section>

{% endif %} {% endfor %}

<div class="col-sm-12">
    <a><button class="addMore" onclick="addMoreItems({{ tableNumber }})">Add More Items</button></a>
</div>

<section id="total">
    <div class="container-fluid">
        <div class="row">

            <div class="col-xs-7">
                <p class="lefts" style="font-weight: bolder">GRAND TOTAL</p>

                <p class="left" style="font-size: 13px">(Taxes & charges included)</p>
            </div>
            <div class="col-xs-5">
                <p class="grandtotal" data-id="{{ order.get_total_unordered }}" style="font-weight: bolder">€ {{ order.get_total_unordered }}</p>
            </div>

        </div>

</section>


<!--Bring Before Label  -->
<div class="row" id="bring">
    <div class="col-xs-8">
        <label for="bring">Bring starters along with main course</label>
    </div>
    <div class="col-xs-4">
        <label class="switchb">
                       <input type="checkbox" class="starters">
                       <span class="sliderb round"></span>
                 </label>
    </div>
</div>
<!--Bring Before Label  -->
<br>

<!--Place Order Fixed-->
<div class="col-sm-12"><button id="orderButton" class="btn btn-lg" onclick="placeOrder({{ tableNumber }})">Place Order</button></div>
<!--Place Order Fixed-->
{% endblock %} {% if messages %} {% for message in messages %}
<div class="modal1 animated slideInUp" id="modal">
    <div class="modal-dialog">
        <header class="modal-header">Alert</header>
        <section class="modal-content">
            <p>{{ message }}</p>
            <button id="close" class="close-modal1" data-dismiss="alert" onclick="this.parentElement.parentElement.parentElement.style.display='none'">
        Close
      </button>
        </section>
    </div>
</div>
{% endfor %} {% endif %} {% block foot_block %}
<script>
    var addMoreItems_url = '{% url "order:menu" tableNumber=tableNumber %}'
    var success_url = '{% url "order:confirmOrder" tableNumber=tableNumber %}';
    var cart_url = '{% url "order:cart" tableNumber=tableNumber %}';
    var order_url = '{% url "order:order_list" tableNumber=tableNumber %}';
    var itemsCount = {{ order_items.count }};
    var diablePlaceOrderCount = itemsCount;
    if (!itemsCount) {
      document.getElementById("orderButton").disabled = true;
    }
</script>
<script src="{% static 'js/order/cart.js' %}"></script>
{% endblock %}

templates/order/orderCart.html
{% extends "order/base.html" %}
{% load static %}

{% block head_block %}

  	<link rel="stylesheet" href="{% static "css/order/cart.css" %}"/>
  	<script type="text/javascript">
        function preventBack() {
            window.history.forward();
        }

        setTimeout("preventBack()", 0);

        window.onunload = function () { null };
    </script>

{% endblock %}


{% block body_block %}

<!--Pop Up Box-->
<div class="modal" id="modal2" data-animation="mixInAnimations">
  <div class="modal-dialog">
    <header class="modal-header">Call Waiter</header>
    <section class="modal-content">
      <p>Someone will be with you shortly.</p>
      <button id="close" class="close-modal" aria-label="close modal" data-close>
        Close
      </button>
    </section>
  </div>
</div>

<!--Pop Up Box-->

{% if messages %}
{% for message in messages %}

<div class="modal1 animated slideInUp" id="modal">
  <div class="modal-dialog1">
    <header class="modal-header">Alert

    </header>
    <section class="modal-content">
      <p>{{ message }}</p>
      <button id="close" class="close-modal1" data-dismiss="alert" onclick="this.parentElement.parentElement.parentElement.style.display='none'">
        Close
      </button>
    </section>
  </div>
</div>
{% endfor %}
{% endif %}



<!--Navbar Starts Here -->
    <nav id="navbar" class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button style="color: #FFECB1" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span style="background-color: #FFECB1" class="sr-only">Toggle navigation</span>
        <span style="background-color: #FFECB1" class="icon-bar"></span>
        <span style="background-color: #FFECB1" class="icon-bar"></span>
        <span style="background-color: #FFECB1" class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'order:menu' tableNumber=tableNumber %}"><img src="{% static 'images/order/Taj_india_Logo.png' %}" alt=""></a>
      <a  href="#" id="callButton"  class="dropdown dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><img src="{% static 'images/order/waiter.png' %}"></a>
          <ul class="dropdown-menu">
            <li><a href="#" class="open-modal" data-open="modal2" onclick="CallWaiter({{ tableNumber }})"><i class="fas fa-phone-volume"></i>&nbsp;&nbsp; Call Waiter</a></li>
          </ul>

    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'order:menu' tableNumber=tableNumber %}">Menu Card</a></li>
        <li><a href="{% url 'order:cart' tableNumber=tableNumber %}">Cart</a></li>
        <li><a href="{% url 'order:order_list' tableNumber=tableNumber %}">Order Details</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!--Navbar Ends Here-->



<!--Parralax Starts Here-->
    <div class="header" style="background-image: url({% static 'images/order/parallex/cart.jpg' %})">
        <h1 id="heading">Order Placed</h1>
        <h3 id="subheading"><i class="far fa-thumbs-up"></i> Thank you for your order</h3>
    </div>
<!--Parralax Ends Here-->
         {% for order_item in order.item.all %}
         {% if order_item.ordered %}
         <section id="order">
           <div class="container-fluid">
	            <div class="row">
			             <div class="col-xs-7"><p class="itemname">{% if order_item.item %}{% if order_item.item.article_number %}{{ order_item.item.article_number }}. {% endif %}{% endif %}{{ order_item.get_name }}</p></div>
			             <div class="col-xs-5">
			                  <p class="quan">Quantity: {{ order_item.quantity }}</p>
			             </div>
              </div>
              <div class="row">
                    {% if order_item.person %}
          			    <div class="col-xs-7">
          			    <p class="spicelvl">(for {{ order_item.person }} person)</p>
          			    </div>
                    {% endif %}
                    {% if order_item.option1 %}
                    <div class="col-xs-7">
                    <p class="spicelvl">({{ order_item.option1 }})</p>
                    </div>
                    {% else %}
                    <div class="col-xs-7">
                    <p class="spicelvl">Price</p>
                    </div>
                    {% endif %}
                    {% if order_item.option2 %}
                    <div class="col-xs-7">
                      <p class="spicelvl">({{ order_item.option2 }})</p>
                    </div>
                    {% endif %}
                    {% if order_item.addOn %}
                    <div class="col-xs-7">
                    <p class="spicelvl">{{ order_item.addOn }} (+{{ order_item.item.category.addOnPrice }} €)</p>
                    </div>
                    {% endif %}
			             <div class="col-xs-5">
			                  <p class="price">€ {{ order_item.getPrice }}</p>
			             </div>
            </div>
		      </div>
        </section>

         {% endif %}
         {% endfor %}

         <div class="col-sm-12">
         <a href="{% url 'order:menu' tableNumber=tableNumber %}"><button class="addMore">Place New Order</button></a>
     </div>

     <section id="total">
     <div class="container-fluid">
       <div class="row">

      			    <div class="col-xs-7">
      			    <p class="lefts" style="font-weight: bolder">GRAND TOTAL</p>

      			    <p class="left" style="font-size: 13px">(VAT included)</p>
      			</div>
      			<div class="col-xs-5">
      			    <p class="grandtotal" style="font-weight: bolder">€ {{ order.get_total_ordered }}</p>
      			</div>

     		</div>

     </section>


     <!--Content Here-->


     <p class="thumbs"><i class="far fa-thumbs-up"></i></p>
     <p class="thanks">Your food is being prepared in the kitchen, it will be served shortly.</p>

     <!--Bring Before Label  -->
         <div class="row" id="bring">
             <div class="col-xs-8">
                  <label for="bring">Do you want to split bill</label>
             </div>
             <div class="col-xs-4">
                 <label class="switchb">
                       <input type="checkbox" class="starters">
                       <span class="sliderb round"></span>
                 </label>
             </div>
         </div>
     <!--Bring Before Label  -->
     <br>

      <!--Place Order Fixed-->

         <div class="col-sm-12"><button id="orderButton" class="btn btn-lg" onclick="window.location.href = '{% url "order:thanks" tableNumber=tableNumber %}'">Request Bill</button></div>
     <!--Place Order Fixed-->
{% endblock %}

{% block foot_block %}
    <script>
      if (!{{ order_items.count }}){
        document.getElementById("orderButton").disabled = true;
      }
    </script>
  	<script src="{% static 'js/order/cart.js' %}"></script>
{% endblock %}